/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud.product;

import crud.product.api.ProductAPI;
import crud.product.models.Produit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naim_
 */
public class MainMenu extends javax.swing.JFrame {

    List<Produit> listProducts;
    ProductAPI productAPI = new ProductAPI();

    public static Produit produit;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

        // initialise le tableau
        initArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        btnAddProductMM = new javax.swing.JButton();
        btnShowProductMM = new javax.swing.JButton();
        btnUpdateProductMM = new javax.swing.JButton();
        btnDeleteProductMM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CRUD Product");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Désignation", "Description", "Quantité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProducts);
        if (jTableProducts.getColumnModel().getColumnCount() > 0) {
            jTableProducts.getColumnModel().getColumn(0).setResizable(false);
            jTableProducts.getColumnModel().getColumn(1).setResizable(false);
            jTableProducts.getColumnModel().getColumn(2).setResizable(false);
            jTableProducts.getColumnModel().getColumn(3).setResizable(false);
        }

        btnAddProductMM.setText("Add Product");
        btnAddProductMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductMMActionPerformed(evt);
            }
        });

        btnShowProductMM.setText("Show Product");
        btnShowProductMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProductMMActionPerformed(evt);
            }
        });

        btnUpdateProductMM.setText("Update Product");
        btnUpdateProductMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductMMActionPerformed(evt);
            }
        });

        btnDeleteProductMM.setText("Delete Product");
        btnDeleteProductMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddProductMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowProductMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateProductMM, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btnDeleteProductMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProductMM)
                        .addGap(48, 48, 48)
                        .addComponent(btnShowProductMM)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateProductMM)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProductMM)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void initArray() {
        buttonState(false);
        listProducts = productAPI.showAll();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"#", "Désignation", "Description", "Quatité"});
        jTableProducts.setModel(dtm);

        for (Produit p : listProducts) {
            dtm.addRow(new Object[]{
                p.getId(), p.getDesignation(), p.getDescription(), p.getQte()
            });
        }
    }

    private void btnAddProductMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductMMActionPerformed

        AddProductFrame addProductFrame = new AddProductFrame();
        addProductFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddProductMMActionPerformed

    private void jTableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductsMouseClicked
        int row = jTableProducts.rowAtPoint(evt.getPoint());
        if (row >= 0 && row <= listProducts.size()) {
            buttonState(true);
            produit = listProducts.get(row);
            System.out.println(produit.toString());
        }
    }//GEN-LAST:event_jTableProductsMouseClicked

    private void btnUpdateProductMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductMMActionPerformed
        UpdateProductFrame updateProductFrame = new UpdateProductFrame();
        updateProductFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateProductMMActionPerformed

    private void btnDeleteProductMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductMMActionPerformed

        productAPI.delete(produit);
        JOptionPane.
                showMessageDialog(null, "produit supprimer");
        initArray();
    }//GEN-LAST:event_btnDeleteProductMMActionPerformed

    private void btnShowProductMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProductMMActionPerformed
        ShowProductFrame showProductFrame = new ShowProductFrame();
        showProductFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnShowProductMMActionPerformed

    private void buttonState(boolean b) {
        btnShowProductMM.setEnabled(b);
        btnUpdateProductMM.setEnabled(b);
        btnDeleteProductMM.setEnabled(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProductMM;
    private javax.swing.JButton btnDeleteProductMM;
    private javax.swing.JButton btnShowProductMM;
    private javax.swing.JButton btnUpdateProductMM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducts;
    // End of variables declaration//GEN-END:variables

}
