/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud.product;

import crud.product.api.ProductAPI;
import crud.product.dao.ProductDao;
import crud.product.models.Produit;
import javax.swing.JOptionPane;

/**
 *
 * @author naim_
 */
public class UpdateProductFrame extends javax.swing.JFrame {

    int produit_id;
    Produit produit;
    ProductAPI productAPI = new ProductAPI();

    /**
     * Creates new form UpdateProductFrame
     */
    public UpdateProductFrame() {
        initComponents();

        produit = productAPI.showById(MainMenu.produit.getId());

        textFieldDesignationUP.setText(produit.getDesignation());
        textFieldDescriptionUP.setText(produit.getDescription());
        textFieldQteUP.setText(String.valueOf(produit.getQte()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldDesignationUP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldDescriptionUP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldQteUP = new javax.swing.JTextField();
        btnCancelUP = new javax.swing.JButton();
        btnSaveUP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(282, 366));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Désignation: ");

        textFieldDesignationUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDesignationUPActionPerformed(evt);
            }
        });

        jLabel2.setText("Description: ");

        jLabel3.setText("Quantité: ");

        btnCancelUP.setText("Cancel");
        btnCancelUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelUPActionPerformed(evt);
            }
        });

        btnSaveUP.setText("Save");
        btnSaveUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Update Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelUP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnSaveUP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldDescriptionUP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldDesignationUP)
                                    .addComponent(textFieldQteUP)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldDesignationUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldDescriptionUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldQteUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelUP)
                    .addComponent(btnSaveUP))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDesignationUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDesignationUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDesignationUPActionPerformed

    private void btnSaveUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUPActionPerformed

        String designation = textFieldDesignationUP.getText();
        String description = textFieldDescriptionUP.getText();
        String qte = textFieldQteUP.getText();

        // validation data
        if (designation.isEmpty()) {
            JOptionPane.
                    showMessageDialog(null, "svp entrez la désignation");
        } else if (description.isEmpty()) {
            JOptionPane.
                    showMessageDialog(null, "svp entrez la description");
        } else if (qte.isEmpty()) {
            JOptionPane.
                    showMessageDialog(null, "svp entrez la quantité");
        } else {
            // insert data
            produit.setDesignation(designation);
            produit.setDescription(description);
            produit.setQte(Integer.valueOf(qte));

            ProductAPI productAPI = new ProductAPI();
            productAPI.update(produit);
            JOptionPane.
                    showMessageDialog(null, "produit modifier");
        }
        onBackPressed();
        // navigate to Main Menu
    }//GEN-LAST:event_btnSaveUPActionPerformed

     private void onBackPressed() {

         // navigation entre les interfaces
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        this.dispose();
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void btnCancelUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUPActionPerformed
        onBackPressed();
    }//GEN-LAST:event_btnCancelUPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelUP;
    private javax.swing.JButton btnSaveUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textFieldDescriptionUP;
    private javax.swing.JTextField textFieldDesignationUP;
    private javax.swing.JTextField textFieldQteUP;
    // End of variables declaration//GEN-END:variables
}
